language: ruby
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
cache: bundler
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer _site/ --alt-ignore '/.*/' --assume-extension --allow-hash-href --enforce-https --url-ignore /vimeo\.com/
rvm:
 - 2.5.3

